LO30/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LO30.Models;
using LO30.Services;
using System.Web.Security;

namespace LO30.Controllers
{
  public class NavigationController : Controller
  {
    public NavigationController()
    {
    }

    [ChildActionOnly]
    public ActionResult Menu()
    {

      try
      {
#if DEBUG
        return PartialView("NavAdmin");
#else
        if (Roles.IsUserInRole("admin"))
        {
          return PartialView("NavAdmin");
        }
        else if (Roles.IsUserInRole("board"))
        {
          return PartialView("NavBoard");
        }
#endif
      } 
      catch (Exception ex)
      {
        System.Diagnostics.Debug.Print("Could not determine the user role, defaulting to public.");
        ErrorHandlingService.PrintFullErrorMessage(ex);
      }

      return PartialView("NavPublic");
    }

  }
}

LO30/Views/Shared/_Layout - Orig.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

LO30/Views/Shared/_Layout-New.cshtml
<!DOCTYPE html>
<!--[if IE 8]>			<html class="ie ie8"> <![endif]-->
<!--[if IE 9]>			<html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->
<html data-ng-app="@ViewBag.InitModule">
<!--<![endif]-->
<head>

  <meta charset="utf-8" />
  <title>@ViewBag.Title - LO30</title>
  <meta name="keywords" content="Hockey,Livonia,Over30s" />
  <meta name="description" content="" />
  <meta name="Author" content="Dan Hunt" />
  <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

  <!-- mobile settings -->
  <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />

  <!-- WEB FONTS -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet" type="text/css" />

  <!-- CORE CSS -->
  <link href="~/Content/Template/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <link href="~/Content/Template/css/font-awesome.css" rel="stylesheet" type="text/css" />
  <link href="~/Content/Template/plugins/owl-carousel/owl.carousel.css" rel="stylesheet" type="text/css" />
  <link href="~/Content/Template/plugins/owl-carousel/owl.theme.css" rel="stylesheet" type="text/css" />
  <link href="~/Content/Template/plugins/owl-carousel/owl.transitions.css" rel="stylesheet" type="text/css" />
  <link href="~/Content/Template/plugins/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css" />
  <link href="~/Content/Template/css/animate.css" rel="stylesheet" type="text/css" />
  <link href="~/Content/Template/css/superslides.css" rel="stylesheet" type="text/css" />

  <!-- REVOLUTION SLIDER -->
  <link href="~/Content/Template/plugins/revolution-slider/css/settings.css" rel="stylesheet" type="text/css" />

  <!-- THEME CSS -->
  <link href="~/Content/Template/css/essentials.css" rel="stylesheet" type="text/css" />
  <link href="~/Content/Template/css/layout.css" rel="stylesheet" type="text/css" />
  <link href="~/Content/Template/css/layout-responsive.css" rel="stylesheet" type="text/css" />
  <link href="~/Content/Template/css/color_scheme/darkblue.css" rel="stylesheet" type="text/css" /><!-- blue: default style -->
  <link id="css_dark_skin" href="~/Content/Template/css/layout-responsive.css" rel="stylesheet" type="text/css" /><!-- DARK SKIN -->
  <!-- Morenizr -->
  <script type="text/javascript" src="~/Content/Template/plugins/modernizr.min.js"></script>

  <!-- app overrides-->
  <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body class="boxed pattern1">
  <!-- Available classes for body: boxed , pattern1...pattern10 . Background Image - example add: data-background="~/Content/Template/images/boxed_background/1.jpg"  -->
  <!-- TOP NAV -->
  <header id="topNav">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="row">
          <div class="navbar-header">
            <!-- Mobile Menu Button -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <i class="fa fa-bars"></i>
            </button>

            <a class="navbar-brand" href="/">&nbsp;&nbsp;Livonia Over 30 Hockey</a>
          </div>

          <!-- Top Nav -->
          @Html.Action("Menu", "Navigation", new { area = "" })
          <!-- /Top Nav -->

        </div>
      </div>
    </nav>
  </header>

  <span id="header_shadow"></span>
  <!-- /TOP NAV -->
  <div id="body">
    @RenderSection("featured", required: false)
    <!-- WRAPPER -->
    <div id="wrapper">
      @RenderBody()
    </div>
    <!-- /WRAPPER -->
  </div>

  <!-- FOOTER -->
  <footer>

    <!-- copyright , scrollTo Top -->
    <div class="footer-bar">
      <div class="container">
        <span class="copyright">Copyright &copy; Livonia Over 30 Hockey. All Rights Reserved.</span>
        <a class="toTop" href="#topNav">BACK TO TOP <i class="fa fa-arrow-circle-up"></i></a>
      </div>
    </div>
    <!-- copyright , scrollTo Top -->
  </footer>
  <!-- /FOOTER -->
  <!-- JAVASCRIPT FILES -->
  <script type="text/javascript" src="~/Content/Template/plugins/jquery-2.0.3.min.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/jquery.easing.1.3.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/jquery.cookie.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/jquery.appear.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/jquery.isotope.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/masonry.js"></script>

  <script type="text/javascript" src="~/Scripts/angular.min.js"></script>
  <script type="text/javascript" src="~/Scripts/angular-route.min.js"></script>
  <script type="text/javascript" src="~/Scripts/angular-resource.min.js"></script>

  <script type="text/javascript" src="~/Content/Template/plugins/bootstrap/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/magnific-popup/jquery.magnific-popup.min.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/owl-carousel/owl.carousel.min.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/stellar/jquery.stellar.min.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/knob/js/jquery.knob.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/jquery.backstretch.min.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/superslides/dist/jquery.superslides.min.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/styleswitcher/styleswitcher.js"></script><!-- STYLESWITCHER - REMOVE ON PRODUCTION/DEVELOPMENT -->
  <script type="text/javascript" src="~/Content/Template/plugins/mediaelement/build/mediaelement-and-player.min.js"></script>

  <!-- REVOLUTION SLIDER -->
  <script type="text/javascript" src="~/Content/Template/plugins/revolution-slider/js/jquery.themepunch.plugins.min.js"></script>
  <script type="text/javascript" src="~/Content/Template/plugins/revolution-slider/js/jquery.themepunch.revolution.min.js"></script>
  <script type="text/javascript" src="~/Scripts/slider_revolution.js"></script>

  <script type="text/javascript" src="~/Scripts/scripts.js"></script>

  <!-- Google Analytics: Change UA-XXXXX-X to be your site's ID. Go to http://www.google.com/analytics/ for more information. -->
  <!--<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-XXXXX-X', 'domainname.com');
      ga('send', 'pageview');
  </script>
  -->
  @RenderSection("scripts", required: false)

</body>
</html>